# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b96a7cf75c8e8f628a85836db58c502d4388fccf0529f858bf368499104e833c04f6204f91b5e061845ae5c370f9a6c411c9424b66c118271f05d0dd37ae4b81

test:
  secret_key_base: b4cc76d5f5ad013de6702dad024067fbfa6e6eff6615108fd8f85397035241ed3604fed8f0a47016a8d96aa0b4a32eefd5d91f2919d5dfc3d6fb460e90db6f2a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
